---
hero_image: images/turtle-race.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Schildpad Race!
description: Race met schildpadden tegen elkaar!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Inleiding
- title: Wat heb je nodig
  completion: engaged
- title: Racebaan
- title: 'Uitdaging: meer lijnen'
- title: Raceschildpadden
- title: 'Uitdaging: racetijd!'
- title: 'Uitdaging: maak een draai'
  completion: internal
- title: 'Uitdaging: stippellijnen'
