---
hero_image: images/turtle-race.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: カメのレース！
description: Race turtles against each other!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: はじめに
  - 
    title: 必要なもの
  - 
    title: レーストラック
  - 
    title: 'チャレンジ：もっと線を描いてみよう'
  - 
    title: カメのレース
  - 
    title: 'チャレンジ：レースの時間！'
  - 
    title: 'チャレンジ：くるくる回してみよう'
  - 
    title: 'チャレンジ：破線を描いてみよう'
