---
hero_image: images/turtle-race.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Ras Crwbanod!
description: Rasiwch grwbanod yn erbyn ei gilydd!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Cyflwyniad
- title: Beth fydd ei angen arnoch chi
  completion: engaged
- title: Trac rasio
- title: 'Her: Mwy o linellau'
- title: Crwbanod rasio
- title: 'Her: Amser ras!'
- title: 'Her: Gwnewch droelliad'
  completion: internal
- title: 'Her: Llinellau toredig'
