---
hero_image: images/turtle-race.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Cursa de tortugues!
description: Cursa de tortugues l’una contra l’altra!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introducció
- title: Què necessitaràs
- title: Circuit de carreres
- title: 'Repte: més línies'
- title: Tortugues corredores
  completion:
  - engaged
  - internal
- title: 'Repte: temps de cursa!'
- title: 'Repte: fer una pirueta'
- title: 'Repte: línies discontinues'
