---
hero_image: images/turtle-race.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Trka kornjača!
description: Napravi da se kornjače trkaju!
original_url: https://codeclubprojects.org/en-GB/python/turtle-race
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
- title: Šta će ti biti potrebno
- title: Trkalište
- title: 'Izazov: Više linija'
- title: Kornjače za trku
  completion:
  - engaged
  - internal
- title: 'Izazov: Vrijeme je za trku!'
- title: 'Izazov: Napravi zaokret'
- title: 'Izazov: Isprekidane linije'
